Написал скрипт который отображает номер в кнопке.
111Mihail111/HanWork pull request #11
Opened 2022-01-15 17:26 UTC by DjWaRCovAiK

2022-01-15 17:31 UTC, JEN1011 requested changes

2022-01-15 17:31 UTC, JEN1011 commented on pages/index.html
> +                                    </div>
Откати строку на то как было, ты создал конфликт для ветки master

2022-01-15 17:33 UTC, 111Mihail111 commented on pages/index.html
> +                                    </div>
Объясню  как это вышло. В предыдущей задаче ты добавил в эту строку картинки, а в этой ты добавил в эту строчку пустоту между дивами. И теперь гит не знает какое изменение эталонное.

2022-01-15 17:34 UTC, 111Mihail111 requested changes

2022-01-15 17:34 UTC, 111Mihail111 commented on bootstrap/js/custom-scripts.js
> +}
Пометь свою функцию с обеих сторон /**/ и внутри напиши комментарий что делает твоя функция. Комментарий должен быть краткий, но понятный.

2022-01-17 16:39 UTC, 111Mihail111 approved these changes

2022-01-17 16:44 UTC, merged