Реализовал открытие модалки по нажатию назвездочку
111Mihail111/HanWork pull request #15
Opened 2022-01-24 18:46 UTC by JEN1011

2022-01-25 12:40 UTC, 111Mihail111 approved these changes

2022-01-25 12:40 UTC, 111Mihail111 commented on bootstrap/js/custom-scripts.js
> +var backToCard = false;
Осмысленное название

2022-01-25 12:40 UTC, 111Mihail111 commented on bootstrap/js/custom-scripts.js
> +var backToCard = false;
И коммент оставь,  чтобы понять что это и для чего

2022-01-25 12:40 UTC, 111Mihail111 commented on bootstrap/js/custom-scripts.js
> +var backToCard = false;
в onclick где кнопка "Подтвердить" сунь переменную и сбрось ее состояние

2022-01-25 12:42 UTC, 111Mihail111 requested changes

2022-01-25 12:42 UTC, 111Mihail111 commented on bootstrap/js/custom-scripts.js
> +var backToCard = false;
в onclick где кнопка "Подтвердить" сунь переменную и сбрось ее состояние

2022-01-26 13:44 UTC, DjWaRCovAiK commented
Одобрено.

2022-01-26 13:46 UTC, DjWaRCovAiK approved these changes
Одобрено.

2022-01-29 07:08 UTC, 111Mihail111 requested changes

2022-01-30 07:42 UTC, 111Mihail111 approved these changes

2022-01-30 07:42 UTC, merged