Master 21
111Mihail111/HanWork pull request #16
Opened 2022-02-07 14:59 UTC by DjWaRCovAiK

2022-02-08 16:37 UTC, JEN1011 approved these changes

2022-02-09 15:33 UTC, 111Mihail111 requested changes

2022-02-09 15:33 UTC, 111Mihail111 commented on pages/profile.html
> +                                                                <img src="..//images/ImageNotFound.jpg" width="100%" height="100%" />
Один слеш в ссылке

2022-02-09 15:33 UTC, 111Mihail111 commented on pages/profile.html
> +                                                                        style="font-weight: 500; border: 2px solid#92d050; border-radius: 4px; color: #92d050; width: 120px;">
Втяни себе изменения с мастера. Там для этих тегов есть классы

2022-02-09 15:33 UTC, 111Mihail111 commented on pages/profile.html
> +                                        <div style="background: white; border-radius: 12px;">
В описании задачи написано, сделать 4 таких карточки

2022-02-09 19:51 UTC, 111Mihail111 approved these changes

2022-02-09 20:07 UTC, merged