#Задача 11: Создал интерфейс просмотра доп. инфы по карте с вакансией
111Mihail111/HanWork pull request #8
Opened 2022-01-13 16:36 UTC by DjWaRCovAiK

2022-01-14 18:45 UTC, JEN1011 requested changes

2022-01-14 18:45 UTC, JEN1011 commented on pages/index.html
> +                            </dov>
Исправь этот непонятный тег на <div>

2022-01-14 18:45 UTC, JEN1011 commented on pages/index.html
> +                                        <button class="btn ms-1" style="width: 30px; height: 30px;" data-bs-toggle="modal" data-bs-target="#exampleModal"
И вот здесь не забудь поменять id в data-bs-target, иначе модальное окно не будет работать

2022-01-14 18:45 UTC, JEN1011 commented on pages/index.html
> +                            <h1 class="modal-title fw-1 fs-cust-7" id="singUpAndLogin" style="margin-left: 56px;">
Удали Id, он здесь не нужен

2022-01-14 18:45 UTC, JEN1011 commented on bootstrap/js/custom-scripts.js
> +}
Это функция urlCopy не нужна, удали ее, она нигде не используется

2022-01-14 19:28 UTC, 111Mihail111 commented on pages/index.html
> +                            </dov>
(dov на div)

2022-01-15 14:07 UTC, JEN1011 approved these changes

2022-01-15 14:08 UTC, 111Mihail111 requested changes

2022-01-15 14:08 UTC, 111Mihail111 commented on pages/index.html
> +    <div class="modal fade" id="ToShapeModal" tabindex="-1" data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
id элемента - с маленькой буквы. И удали атрибут aria-labelledby="exampleModalLabel"

2022-01-15 16:09 UTC, 111Mihail111 approved these changes

2022-01-15 16:09 UTC, merged